/**
 * Prompt Exports
 */

export {
  CORE_STORYTELLING_PROMPT,
  FICTION_FIRST_PHILOSOPHY,
  STAKES_TRIANGLE,
  CHOICE_GEOMETRY,
  CONSEQUENCE_BUDGETING,
  THREE_LAYER_MEMORY,
  BRANCH_AND_BOTTLENECK,
  QUALITY_MANTRAS,
  // Additional storytelling principles
  FIVE_FACTOR_TEST,
  NPC_DEPTH_TIERING,
  CHOICE_DENSITY_REQUIREMENTS,
} from './storytellingPrinciples';

export {
  VISUAL_STORYTELLING_PROMPT,
  CORE_VISUAL_PRINCIPLE,
  MOBILE_COMPOSITION_FRAMEWORK,
  SHOT_TYPE_SYSTEM,
  CAMERA_ANGLE_SYSTEM,
  BODY_LANGUAGE_VOCABULARY,
  WALLY_WOOD_PANELS,
  SEQUENCE_VARIETY_RULES,
  VISUAL_BEAT_MAPPING,
  FORBIDDEN_DEFAULTS,
  // Pose best practices
  STORY_BEAT_DEFINITION,
  POSE_LINE_OF_ACTION,
  POSE_TILT_RHYTHM_TWIST,
  POSE_ASYMMETRY_RULES,
  POSE_WEIGHT_AND_BALANCE,
  POSE_SILHOUETTE_CLARITY,
  POSE_VOCABULARY,
  COMPOSITION_STORYTELLING,
  LIGHTING_MOOD_VOCABULARY,
  POSE_DIVERSITY_CHECKLIST,
  PROMPT_ASSEMBLY_PATTERN,
  ENCOUNTER_VISUAL_PRINCIPLES_COMPACT,
  STORY_BEAT_VISUAL_PRINCIPLES_COMPACT,
  BEAT_STAGING_MAP,
  getBeatStagingDirection,
  POSE_PRINCIPLES_COMPACT,
  // Panel transition system
  TRANSITION_TYPES,
  TRANSITION_SELECTION_RULES,
  TRANSITION_CONTINUITY_RULES,
  TRANSITION_PROMPT_TEMPLATES,
} from './visualPrinciples';
