/**
 * LLM Output Types
 * 
 * These types represent the simplified structures that LLMs output.
 * They are designed to be flat and simple to reduce hallucination risk.
 * 
 * These types get converted to the full types in types/index.ts via
 * converter functions in ../converters/
 */

// ========================================
// STATE CHANGE (LLM Output Format)
// ========================================

/**
 * StateChange is a simplified type for LLM-generated output.
 * It gets converted to the full Consequence type (from types/index.ts) 
 * via convertStateChangeToConsequence().
 * 
 * Mapping:
 * - 'flag' -> { type: 'setFlag', flag: name, value: change }
 * - 'score' -> { type: 'changeScore', score: name, change: number } or { type: 'setScore' }
 * - 'tag' -> { type: 'addTag' } or { type: 'removeTag' }
 * - 'relationship' -> { type: 'relationship', npcId, dimension, change }
 *   (name format: "npcId:dimension" e.g., "mayor:trust")
 */
export interface StateChange {
  type: 'flag' | 'score' | 'tag' | 'relationship';
  name: string;
  change: string | number | boolean;
}

// ========================================
// STORYLET (LLM Output Format)
// ========================================

/**
 * StoryletBeat as output by the LLM.
 * Uses StateChange[] for consequences which gets converted to Consequence[].
 */
export interface LLMStoryletBeat {
  id: string;
  text: string;
  speakerName?: string;
  speakerMood?: string;
  choices?: Array<{
    id: string;
    text: string;
    nextBeatId?: string;
    consequences?: StateChange[];
  }>;
}

/**
 * GeneratedStorylet as output by the LLM.
 * Uses StateChange[] for consequences which gets converted to Consequence[].
 */
export interface LLMGeneratedStorylet {
  outcomeText: string;
  beats: LLMStoryletBeat[];
  consequences?: StateChange[];
  nextSceneId?: string;
}

// ========================================
// ENCOUNTER CHOICE OUTCOME (LLM Output Format)
// ========================================

/**
 * EncounterChoiceOutcome as output by the LLM.
 * Uses StateChange[] which gets converted to Consequence[].
 */
export interface LLMEncounterChoiceOutcome {
  tier: 'success' | 'complicated' | 'failure';
  narrativeText: string;
  goalTicks: number;
  threatTicks: number;
  nextBeatId?: string;
  outcomeImage?: string;
  consequences?: StateChange[];
  
  // Visual direction for this outcome
  visualDirection?: {
    cameraAngle: 'low_heroic' | 'high_diminished' | 'dutch_unstable' | 'eye_level';
    shotType: 'dramatic_closeup' | 'action_wide' | 'reaction_medium' | 'impact_freeze';
    mood: 'triumphant' | 'tense' | 'desperate' | 'bittersweet';
  };
}

// ========================================
// ENCOUNTER STRUCTURE (LLM Output Format)
// ========================================

/**
 * Storylets section of EncounterStructure as output by the LLM.
 */
export interface LLMEncounterStorylets {
  victory?: LLMGeneratedStorylet;
  partialVictory?: LLMGeneratedStorylet;
  defeat?: LLMGeneratedStorylet;
  escape?: LLMGeneratedStorylet;
}

// ========================================
// GENERATED BEAT (LLM Output Format)
// ========================================

/**
 * Beat content as generated by SceneWriter LLM.
 * May include choices with consequences.
 */
export interface LLMGeneratedBeat {
  id: string;
  content: string | {
    narrative?: string;
    text?: string;
    dialogue?: Array<{ speaker: string; text: string }>;
  };
  speaker?: string;
  speakerMood?: string;
  image?: string;
  choices?: Array<{
    id: string;
    text: string;
    consequences?: StateChange[];
    nextBeatId?: string;
    nextSceneId?: string;
  }>;
  nextBeatId?: string;
  nextSceneId?: string;
}

// ========================================
// TYPE GUARDS
// ========================================

/**
 * Type guard to check if an object is a StateChange
 */
export function isStateChange(obj: unknown): obj is StateChange {
  if (typeof obj !== 'object' || obj === null) return false;
  const sc = obj as Record<string, unknown>;
  return (
    typeof sc.type === 'string' &&
    ['flag', 'score', 'tag', 'relationship'].includes(sc.type) &&
    typeof sc.name === 'string' &&
    (typeof sc.change === 'string' || typeof sc.change === 'number' || typeof sc.change === 'boolean')
  );
}

/**
 * Type guard to check if an array contains StateChange objects
 */
export function isStateChangeArray(arr: unknown): arr is StateChange[] {
  return Array.isArray(arr) && arr.every(isStateChange);
}
