export const PLANNING_REGISTER_LEAK_PATTERNS: Array<{ label: string; pattern: RegExp }> = [
  { label: 'Open the episode', pattern: /\bOpen\s+the\s+episode\b/i },
  { label: 'Introduce X on-page', pattern: /\bIntroduce\s+[^.!?\n]{1,100}?\s+on-page\b/i },
  { label: 'Authored treatment choice', pattern: /\bAuthored\s+treatment\s+choice\b/i },
  { label: 'Authored choice pressure', pattern: /\bauthored\s+choice\s+pressure\b/i },
  { label: 'Next beat response', pattern: /\bnext\s+beat\s+visibly\s+responds\b/i },
  { label: 'Choice response mechanics summary', pattern: /\bThe\s+response\s+changes\s+access,\s*trust,\s*information,\s*or\s*danger\s+around\b/i },
  { label: 'Decide how to handle', pattern: /\bDecide\s+how\s+to\s+handle\b/i },
  { label: 'Development-scene planning stub', pattern: /(?:^|[.!?]\s+)\s*development\s+scene\s+\d+\s*\.?\s*(?:$|[.!?])/i },
  { label: 'Structural peak label', pattern: /(?:^|[.!?]\s+)\s*PEAK\s*:/i },
  { label: 'Cold-open prelude wrapper', pattern: /\bCold-open\s+prelude\s*:/i },
  { label: 'Planned scene continuation wrapper', pattern: /\bThen\s+continue\s+into\s+the\s+planned\s+scene\s*:/i },
  { label: 'Sequence staging directive', pattern: /\bStage\s+the\s+pressure\s+through\s+visible\s+action,\s*reaction,\s*object\s+movement,\s*distance,\s*or\s+dialogue\s+around\b/i },
  { label: 'Cold-open moment instruction', pattern: /\bOpen\s+with\s+this\s+cold-open\s+moment\b/i },
  { label: 'Required cold-open prelude instruction', pattern: /\bOpen\s+on\s+the\s+required\s+cold-open\s+prelude\b/i },
  { label: 'Aftermath stakes reset', pattern: /\bAftermath\s+that\s+resettles\s+stakes\b/i },
  { label: 'Hook/promise/stakes treatment labels', pattern: /\bHook\s*(?:—|-|:)[^.!?\n]{0,700}\bpromise\s*(?:—|-|:)[^.!?\n]{0,700}\bstakes\s*(?:—|-|:)/i },
  { label: 'Treatment structural label', pattern: /^\s*(?:Hook|promise|stakes)\s*(?:—|-|:)/i },
  { label: 'Embedded treatment structural label', pattern: /\b(?:around|because)\s+(?:Hook|promise|stakes)\s*(?:—|-|:)/i },
  { label: 'Treatment gag thesis card', pattern: /\bA\s+FaceTime\s+gag\s+that\s+quietly\s+seeds\s+everything\b/i },
  { label: 'Treatment first-strong-image label', pattern: /\bFirst\s+strong\s+image\s*:/i },
  { label: 'Treatment thesis disguise note', pattern: /\bseason['’]s\s+thesis\s+in\s+disguise\b/i },
  { label: 'Treatment ordinary-world card', pattern: /\bordinary\s+world\s+is\s+[^.!?\n]{1,180}/i },
  { label: 'Treatment grandmother-address fragment', pattern: /(?:^|[.!?]\s+)(?:her|his|their|your)\s+grandmother['’]s\s+address\s*[.!?](?:\s|$)/i },
  { label: 'Treatment protection-strategy card', pattern: /\bprotects\s+herself\s+(?:the\s+way\s+she\s+always\s+has|by\s+observing|through\s+observing)\b/i },
  { label: 'Treatment opening-promise label', pattern: /\bOpening\s+promise\s*:/i },
  { label: 'Treatment reinvention-as-performance shard', pattern: /\breinvention-as-performance\b/i },
  { label: 'Structural beat service', pattern: /\bserves\s+the\s+(?:hook|plotTurn1|pinch1|midpoint|pinch2|climax|resolution)\s+beat\b/i },
  { label: 'Forward pressure', pattern: /\bForward\s+pressure\s*:/i },
  { label: 'Episode pressure instruction', pattern: /\bEscalate\s+the\s+episode\s+pressure\s+through\s+a\s+concrete\s+turn\s*:/i },
  { label: 'Fallout pressure instruction', pattern: /\bLet\s+the\s+fallout\s+settle\s+into\s+the\s+next\s+pressure\s*:/i },
  { label: 'Scene pressure fallback', pattern: /\bthe\s+scene\s+pressure\s+sharpens\s+into\s+a\s+visible\s+turning\s+point\b/i },
  { label: 'Room leverage fallback', pattern: /\bchanges\s+the\s+room['’]s\s+leverage\s+through\b/i },
  { label: 'Beat beneath words fallback', pattern: /\breveal\s+the\s+beat\s+beneath\s+the\s+words\b/i },
  { label: 'Selected route scene-change fallback', pattern: /\bThe\s+selected\s+(?:route|choice)\s+changes\s+the\s+next\s+scene\b/i },
  { label: 'Path player chose fallback', pattern: /\b(?:later\s+narration\s+remembers\s+which|which)\s+path\s+the\s+player\s+chose\b/i },
  { label: 'Next-scene consequence directive', pattern: /\b(?:will|should|must|can)\b[^.!?\n]{0,180}\bnext\s+scene\b/i },
  { label: 'Next-scene pressure fallback', pattern: /\bnext[-\s]+scene\s+pressure\b/i },
  { label: 'Grounded transition into next scene fallback', pattern: /\bprovide\s+aftermath\s+or\s+a\s+grounded\s+transition\s+into\s+the\s+next\s+scene\b/i },
  { label: 'Attention pressures next scene fallback', pattern: /\b(?:viral|public)\s+attention\s+pressure\s+the\s+next\s+scene\b/i },
  { label: 'Changed state into next scene fallback', pattern: /\bHand\s+the\s+changed\s+state\s+into\s+the\s+next\s+scene\b/i },
  { label: 'Protagonist next-scene bridge', pattern: /\bthe\s+protagonist\s+carries\s+the\s+consequence\s+forward\s+before\s+the\s+next\s+scene\s+begins\b/i },
  { label: 'Story earn next scene bridge', pattern: /\bthe\s+story\s+must\s+earn\s+the\s+next\s+scene\s+before\s+it\s+begins\b/i },
  { label: 'World pattern feedback fallback', pattern: /\bThe\s+world\s+gives\s+up\s+a\s+little\s+more\s+of\s+its\s+pattern\b/i },
  { label: 'Information ledger label', pattern: /\binformation\s+ledger\b/i },
  { label: 'Raw INFO token', pattern: /\bINFO[-_\s]+[A-Z0-9][A-Z0-9_-]*\b/i },
];

export function isPlanningRegisterText(text: string | undefined): boolean {
  if (!text || text.trim().length === 0) return false;
  return PLANNING_REGISTER_LEAK_PATTERNS.some(({ pattern }) => pattern.test(text));
}
