/**
 * Story Exporter
 *
 * Converts generated Story objects into TypeScript files
 * that can be dropped directly into src/data/stories/
 */

import { Story } from '../../types';

/**
 * Generate a TypeScript file content from a Story object
 */
export function storyToTypeScript(story: Story, variableName?: string): string {
  const varName = variableName || toCamelCase(story.title);

  const content = `import { Story } from '../../types';

/**
 * ${story.title}
 * ${story.synopsis}
 *
 * Generated by AI Story Pipeline
 * Genre: ${story.genre}
 */

export const ${varName}: Story = ${JSON.stringify(story, null, 2)
    .replace(/"([^"]+)":/g, '$1:')  // Remove quotes from keys
    .replace(/"/g, "'")              // Use single quotes for strings
    .replace(/'(\d+)'/g, '$1')       // Remove quotes from numbers
    .replace(/'(true|false)'/g, '$1') // Remove quotes from booleans
    .replace(/'null'/g, 'null')      // Fix null values
  };
`;

  return content;
}

/**
 * Generate the index.ts export line for a new story
 */
export function generateIndexExport(story: Story, variableName?: string): string {
  const varName = variableName || toCamelCase(story.title);
  const fileName = toKebabCase(story.title);

  return `export { ${varName} } from './${fileName}';`;
}

/**
 * Get the suggested filename for a story
 */
export function getStoryFileName(story: Story): string {
  return `${toKebabCase(story.title)}.ts`;
}

/**
 * Convert a title to camelCase variable name
 */
function toCamelCase(str: string): string {
  return (str || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/^./, char => char.toLowerCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

/**
 * Convert a title to kebab-case filename
 */
function toKebabCase(str: string): string {
  return (str || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Validate that a generated story has required fields
 */
export function validateStoryForExport(story: Story): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!story.id) errors.push('Missing story ID');
  if (!story.title) errors.push('Missing story title');
  if (!story.genre) errors.push('Missing story genre');
  if (!story.synopsis) errors.push('Missing story synopsis');
  if (!story.episodes || story.episodes.length === 0) {
    errors.push('Story has no episodes');
  }

  for (const episode of story.episodes || []) {
    if (!episode.scenes || episode.scenes.length === 0) {
      errors.push(`Episode ${episode.id} has no scenes`);
    }
    for (const scene of episode.scenes || []) {
      if (!scene.beats || scene.beats.length === 0) {
        errors.push(`Scene ${scene.id} has no beats`);
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Format a Story object for pretty printing
 */
export function formatStoryStats(story: Story): string {
  let totalBeats = 0;
  let totalChoices = 0;

  for (const episode of story.episodes) {
    for (const scene of episode.scenes) {
      totalBeats += scene.beats.length;
      for (const beat of scene.beats) {
        if (beat.choices) {
          totalChoices += beat.choices.length;
        }
      }
    }
  }

  return `
Story: ${story.title}
Genre: ${story.genre}
Episodes: ${story.episodes.length}
NPCs: ${story.npcs.length}
Total Scenes: ${story.episodes.reduce((acc, ep) => acc + ep.scenes.length, 0)}
Total Beats: ${totalBeats}
Total Choices: ${totalChoices}
`.trim();
}
